# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: izmailoff
email: izmailoff@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about best programming practices, tricks and maybe some machine learning.
  Topics: Functional Programming (FP), Object Oriented Programming (OOP),
  Machine Learning (ML), Big Data, performance, coding, and ranting about programming life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://izmailoff.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AlekseyIzmailov
github_username:  izmailoff

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title/

# Google Analytics
google_analytics: UA-112122335-1

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    shortname: izmailoff

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
